#!/bin/bash
##############################################
# $Author: netkiller $
# $Id$
# http://netkiller.github.io
##############################################
BASEDIR='/usr/local'
PROG=$BASEDIR/bin/collection
NAME=$(basename $PROG)
LOGFILE=/var/tmp/$NAME.log
PIDFILE=/var/tmp/$NAME.pid
##############################################
#echo $$
#echo $BASHPID
LOGDIR=/tmp/log
##############################################
DEBUG='Y'
##############################################

function run(){

	while read port log
	do
		if [ $DEBUG == 'Y' ]; then
			echo $port $log
		fi
		dirpath=$(dirname $log)
		if [ ! -d $dirpath ]; then
			mkdir -p $dirpath
		fi
		${PROG} -d -p $port -l $log
	done << EOF
1214 /tmp/var/log/auth.log
1215 /tmp/var/log/dmesg
1216 /tmp/var/log/syslog
1217 /tmp/var/log/nginx/access.log	
1218 /tmp/nginx/access.log
1219 ${LOGDIR}/test.log
1220 /tmp/app/$(date +"%Y-%m-%d.%H:%M:%S").log
1221 /tmp/db/$(date +"%Y-%m-%d")/mysql.log
1222 /tmp/cache/$(date +"%Y")/$(date +"%m")/$(date +"%d")/cache.log
EOF

	#for log in ${LOG}
	#do
	#	${RLOG} $log
	#	echo $! > $PIDFILE
	#done
}

function compress(){
	# $(date -d "yesterday" +"%Y-%m-%d.%H:%M:%S")
	for zlog in $(ls -1 ${LOGDIR}/*.$(date -d "yesterday" +"%Y-%m-%d").log)
	do
		if [ -f $zlog ]; then
			gzip $zlog &
		fi
	done
}

function start(){
	if [ -f "$PIDFILE" ]; then
		echo $PIDFILE
		exit 2
	fi
	run
	compress
	#for (( ; ; ))
	#do
	#done &
}
function stop(){
  	#[ -f $PIDFILE ] && kill `cat $PIDFILE` && rm -rf $PIDFILE
	pkill -x ${NAME}
	[ -f $PIDFILE ] && rm -rf $PIDFILE
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  status)
  	ps ax | grep ${NAME} | grep -v grep | grep -v status
	;;
  restart)
  	stop
	start
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 2
esac

exit $?
