#!/bin/bash
##############################################
# $Author: netkiller $
# $Id$
# http://netkiller.github.io
##############################################
BASEDIR='/usr/local'
PROG=$BASEDIR/bin/rlog
NAME=$(basename $PROG)
LOGFILE=/var/tmp/$NAME.log
PIDFILE=/var/tmp/$NAME.pid
##############################################
HOST=127.0.0.1
PORT=
LOG=""
##############################################
#RLOG="/usr/local/bin/rlog -d -H ${HOST} -p ${PORT} "
RLOG="${PROG}"
DEBUG='N'
##############################################
#echo $$
#echo $BASHPID

function run(){

	while read port user
	do
		history=/home/$user/.bash_history 
		if [ $DEBUG == 'Y' ]; then
			echo $port $user
		fi
		
		if [ -f $history ]; then
			${RLOG} -d --postion -H ${HOST} -p $port $history
		else
			${RLOG} -d -f --postion -H ${HOST} -p $port $history
		fi
	done << EOF
1220 neo
1221 jam
1222 sam
EOF

}

function start(){
	if [ -f "$PIDFILE" ]; then
		echo $PIDFILE
		exit 2
	fi
	run
	
	#for (( ; ; ))
	#do
	#done &
}
function stop(){
	pkill -f .bash_history
	[ -f $PIDFILE ] && rm -rf $PIDFILE
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  status)
  	ps ax | grep .bash_history | grep -v grep | grep -v status
	;;
  restart)
  	stop
	start
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 2
esac

exit $?
